#ifndef COLONY_CONFIG_H_
#define COLONY_CONFIG_H_

// Enable Trace
#define USE_CPL_SYSTEM_TRACE

// BETTER ENUM config...
#define USE_CPL_TYPE_BETTERENUM_ENABLE_DEFAULT_CONSTRUCTOR
#define USE_CPL_TYPE_BETTERENUM_EXTEND_128_32


#endif
